/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Stephen' at '5/8/15 8:50 PM' with Gradle 2.4
 *
 * @author Stephen, @date 5/8/15 8:50 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        boolean foo = true;
        if (!foo) {
          foo = false;
        }
        return true;
    }
}
