import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Stephen' at '5/8/15 8:50 PM' with Gradle 2.4
 *
 * @author Stephen, @date 5/8/15 8:50 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", !classUnderTest.someLibraryMethod());
    }
}
